### ISSUE TITLE
problem evaluating some Git parameters when running on Jenkins

### ISSUE THREAD

**Issue by vincent-fuchs** [cucumber/ci-environment#156]
### 👓 What did you see?

I have a very strange issue with the Cucumber tests when running on Jenkins. I don't know if the problem is with Jenkins, but it fails during the Cucumber test initialization, and it doesn't give much infos to investigate. 

The build runs fine when I build on my main branch. 

I also have another Jenkins job  for hotFix releases that we sometimes need to use : in that case, I provide the branch name, and the Jenkins build will build from that branch instead of the main branch. 

when I run this hotFix job, on the same commit as the main branch (I just create a dummy branch, but don't put any commit in it), my build fails with this stacktrace : 

	java.lang.IllegalArgumentException: named capturing group is missing trailing '}'
		at java.base/java.util.regex.Matcher.appendExpandedReplacement(Matcher.java:1052)
		at java.base/java.util.regex.Matcher.appendReplacement(Matcher.java:908)
		at io.cucumber.cienvironment.VariableExpression.evaluate(VariableExpression.java:26)
		at io.cucumber.cienvironment.CiEnvironmentImpl.detectGit(CiEnvironmentImpl.java:71)
		at io.cucumber.cienvironment.CiEnvironmentImpl.detect(CiEnvironmentImpl.java:63)
		at io.cucumber.cienvironment.DetectCiEnvironment.lambda$detectCiEnvironment$0(DetectCiEnvironment.java:19)
		at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
		at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
		at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
		at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
		at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
		at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
		at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
		at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
		at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
		at io.cucumber.cienvironment.DetectCiEnvironment.detectCiEnvironment(DetectCiEnvironment.java:22)
		at io.cucumber.core.runtime.CucumberExecutionContext.createMeta(CucumberExecutionContext.java:65)
		at io.cucumber.core.runtime.CucumberExecutionContext.emitMeta(CucumberExecutionContext.java:55)
		at io.cucumber.core.runtime.CucumberExecutionContext.startTestRun(CucumberExecutionContext.java:50)
		at io.cucumber.junit.platform.engine.CucumberEngineExecutionContext.startTestRun(CucumberEngineExecutionContext.java:96)

I looked into the code and as the stacktrace suggests, Cucumber at some point tries to get the Git infos, evaluationg `git.remote` : 

![image](https://user-images.githubusercontent.com/9657583/181219013-a0de5d7c-794c-4317-b084-f1e7ef659e56.png)

I assume that the `git.remote` value is incorrect, with a `{` but no` }` , or something like that.. when connecting on my jenkins container, and doing a `git config --list` in the directory where the code is checked out, I don't see anything like that. 

### ✅ What did you expect to see?

a bit more information to be able to investigate the issue.. the actual value of `git.remote` before evaluating it would be useful for instance

### 📦 Which tool/library version are you using?

`cucumber-jvm 7.4.1`
which pulls 
`ci-environment 9.0.4`

### 🔬 How could we reproduce it?

I fully realize that this may be linked to my Jenkins setup, and can't be easily reproduced.. but any pointer wouldbe appreciated.

**Comment by mpkorstanje** [comment]
I suspect that the value of `GIT_URL` is something like `${GIT_URL}`.  This would be a problem when using `Matcher.appendReplacement`. This could be avoided by escaping the input before using it:

https://github.com/cucumber/ci-environment/blob/9452c3b85ae7b7cb95863ad5ff7e093b57f30b05/java/src/main/java/io/cucumber/cienvironment/VariableExpression.java#L26

**Comment by mpkorstanje** [comment]
You explicitly include v9.1.0 as a dependency until it gets released with the next version of cucumber-jvm.

**Comment by vincent-fuchs** [comment]
> You explicitly include v9.1.0 as a dependency until it gets released with the next version of cucumber-jvm. Should be available on Central in a few hours.

Thanks a lot @mpkorstanje : I've upgraded the BOM to 7.6.0 , so now I get `ci-environment 9.1.0` , and now it works.
